language: rust

before_install:
- rustup component add clippy
- rustup component add rustfmt
cache: cargo
script:
- cargo build --verbose --workspace
- cargo test --verbose --workspace
- cargo check --verbose --workspace
- cargo fmt -- --check
- cargo clippy --verbose --workspace